from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel, Field, ConfigDict


# ==========================================================
# HCP SCHEMAS
# ==========================================================

class HCPBase(BaseModel):
    name: str = Field(..., min_length=2, max_length=100)
    specialization: str
    hospital: str


class HCPCreate(HCPBase):
    pass


class HCPResponse(HCPBase):
    id: int

    model_config = ConfigDict(
        from_attributes=True
    )


# ==========================================================
# INTERACTION SCHEMAS
# ==========================================================

class InteractionBase(BaseModel):
    hcp_name: str = Field(..., min_length=2, max_length=100)
    summary: str = Field(..., min_length=5)
    product: str
    follow_up: date

class InteractionCreate(BaseModel):

    hcp_name: str

    summary: str

    product: str

    follow_up: date



class InteractionResponse(BaseModel):

    id: int

    hcp_name: str

    summary: str

    product: str

    follow_up: date


    class Config:

        from_attributes = True

class InteractionCreate(InteractionBase):
    """
    Used while creating a new interaction.
    """
    pass


class InteractionUpdate(BaseModel):
    """
    Used for updating an interaction.
    Every field is optional.
    """

    hcp_name: Optional[str] = None
    summary: Optional[str] = None
    product: Optional[str] = None
    follow_up: Optional[date] = None


class InteractionResponse(InteractionBase):
    """
    Returned after database operations.
    """

    id: int

    model_config = ConfigDict(
        from_attributes=True
    )


# ==========================================================
# CHAT SCHEMAS
# ==========================================================

class ChatRequest(BaseModel):
    """
    Incoming chat message from React frontend.
    """

    message: str


class ChatResponse(BaseModel):
    """
    Response generated by LangGraph + Groq.
    """

    response: str


# ==========================================================
# LANGGRAPH STATE
# ==========================================================

class AgentState(BaseModel):
    """
    Shared state passed between LangGraph nodes.
    """

    user_input: str

    intent: Optional[str] = None

    extracted_entities: Optional[dict] = None

    tool_name: Optional[str] = None

    tool_output: Optional[dict] = None

    final_response: Optional[str] = None


# ==========================================================
# LLM EXTRACTION SCHEMA
# ==========================================================

class ExtractedInteraction(BaseModel):
    """
    Structured information extracted by the LLM.
    """

    doctor_name: str

    product: str

    summary: str

    follow_up: str


# ==========================================================
# NEXT BEST ACTION
# ==========================================================

class NextBestActionResponse(BaseModel):
    recommendation: str


# ==========================================================
# FOLLOW-UP
# ==========================================================

class FollowUpRequest(BaseModel):
    interaction_id: int
    follow_up_date: date


# ==========================================================
# EDIT REQUEST
# ==========================================================

class EditInteractionRequest(BaseModel):
    interaction_id: int

    summary: Optional[str] = None

    product: Optional[str] = None

    follow_up: Optional[date] = None


# ==========================================================
# STANDARD API RESPONSE
# ==========================================================

class APIResponse(BaseModel):
    success: bool
    message: str