from typing import TypedDict, Optional, Any


class AgentState(TypedDict):
    """
    Shared state object used by LangGraph.

    Every node in the graph receives this state
    and returns an updated state.
    """

    # User input message
    message: str


    # Detected user intent
    # Example:
    # log_interaction
    # edit_interaction
    # search_hcp
    # next_best_action
    # follow_up

    intent: Optional[str]


    # Data generated by tools

    tool_result: Optional[Any]


    # Final response returned to user

    response: Optional[str]